plugins {
    id 'groovy'
    id 'application'
}

group = 'com.mariajuliasales'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:5.0.8'
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.spockframework:spock-core:2.4-groovy-5.0'
    testImplementation 'net.bytebuddy:byte-buddy:1.14.9'

}

application {
    mainClass = 'com.mariajuliasales.Main'
}

run {
    standardInput = System.in
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}